# Hyprpaper default configuration
splash = false
ipc = true
preload = __WALLPAPER__

# Nixvader's default display is the internal eDP-1 panel.
wallpaper {
  monitor = eDP-1
  path = __WALLPAPER__
  fit_mode = cover
}


